services:
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
    depends_on:
      - php-fpm
      - database
    networks:
      - app-network

  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    ports:
      - 9000:9000
    build:
      context: ./docker/php-fpm
    volumes:
      - ./docker/php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./api:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  database:
    container_name: ${APP_NAME}_database
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
