services:
  # Nginx
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/log/nginx:/var/log/nginx
      - .:/var/www/html
    depends_on:
      - php-fpm
      - database
    networks:
      - app-network
  # PHP-FPM
  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    ports:
      - 9000:9000
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www/html
    depends_on:
      - database
      - redis
    networks:
      - app-network
  # PostgreSQL
  database:
    container_name: ${APP_NAME}_database
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
      - .:/var/www/html
    networks:
      - app-network
  # Redis
  redis:
    container_name: ${APP_NAME}_redis
    image: redis:${REDIS_VERSION}
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis-data:/data
    networks:
      - app-network
    restart: unless-stopped
  # PHP-CLI (Исскуственное нагрузочное тестирование)
  loadtester:
    container_name: ${APP_NAME}_loadtester
    build:
      context: ./.docker/php-cli
    volumes:
      - ./.loadtester:/app #:rw,uid=1000,gid=1000  # Явное указание прав
    depends_on:
      - php-fpm
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
